<?php

namespace Config;

use Daycry\CronJob\Scheduler;

class CronJob extends \Daycry\CronJob\Config\CronJob
{
	public function init(Scheduler $schedule)
	{
		helper(['common', 'app', 'db', 'module','preferences']);
		parent::init($schedule); // TODO: Change the autogenerated stub
		$core = new \CODE\CronJob();
		$core->run($schedule);
	}
}

?>