name: Build Deploy hrm site
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: self-hosted # or specify the runner you want to use for the build job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          yarn install
          yarn install-all-dep-win
  deploy:
    runs-on: self-hosted # or specify the runner you want to use for the deploy job
    needs: build # Ensure the deploy job needs the 'build' job
    steps:
      - name: Init env
        run: |
          cp Backend/core/env Backend/core/.env
          cp Backend/applications/default/env Backend/applications/default/.env
          cp Frontend/env Frontend/.env
          cp Frontend/env.development Frontend/.env.development
          cp Frontend/env.production Frontend/.env.production
          cp Server/env Server/.env
          cp Server/env.development Server/.env.development
          cp Server/env.production Server/.env.production
      - name: Build and Start Production
        run: |
          yarn run build-app-win
          yarn start-production
      - name: Success
        run: echo "This job is done"
