name: Build Deploy hrm site
on: 
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: 
    - self-hosted
    - hrm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build-app
        run: yarn install
        run: yarn install-all-dep-win
  deploy:
    runs-on: 
      - self-hosted
      - hrm
    needs: build
    steps:
      - name: init env
        run: |
          cp Backend/core/env Backend/core/.env
          cp Backend/applications/default/env Backend/applications/default/.env
          cp Frontend/env Frontend/.env
          cp Frontend/env.development Frontend/.env.development
          cp Frontend/env.production Frontend/.env.production
          cp Server/env Server/.env
          cp Server/env.development Server/.env.development
          cp Server/env.production Server/.env.production
      - name: deploy-app
        run: yarn run build-app-win
        run: yarn start-production
      - name: success
        run: echo " This job is done"